$(document).ready(function(){
  $("#signupform").validate({
    rules:{
      name:{
        required:true,
        minlength:5,
      },
      username:{
        required:true,
        minlength:5,
        unique:true,
        
      },
      password:{
        minlength:6,
        required:true,
      },
      confirmpassword:{
        required:true,
      }
    }
  })
})